name: dev-build
run-name: Build plugin for development
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup PNPM@9
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Lint frontend source
        run: |
          pnpm i
          pnpm run lint:frontend

  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup latest Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          check-latest: true

      - name: Install flake8
        run: pip install flake8

      - name: Lint backend source
        run: flake8 main.py

  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup PNPM@9
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Build frontend from source
        run: |
          pnpm i
          pnpm run build

      - name: Download Decky Plugin CLI
        run: |
          mkdir $(pwd)/cli
          curl -L -o $(pwd)/cli/decky "https://github.com/SteamDeckHomebrew/cli/releases/latest/download/decky-linux-x86_64"
          chmod +x $(pwd)/cli/decky

      - name: Build plugin
        run: |
          $(pwd)/cli/decky plugin build $(pwd)
          unzip out/${{ github.event.repository.name }}.zip -d out/${{ github.event.repository.name }}

      - name: Upload plugin
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: out/${{ github.event.repository.name }}/*
